[package]
name = "food-chain-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
rand = "0.8.3"
bevy_prototype_lyon = "0.5.0"
array-macro = "2.1.5"
